### ISSUE TITLE
TypeError thrown with message "Return value of ilPDOStatement::fetchAssoc() must be of the type array or null, bool returned"

### ISSUE THREAD

**Issue by marvimarv** [srsolutionsag/SrMemberships#2]
Hello,

When using the plugin in our ILIAS 8.8 2024-01-17, we get an error:

[a2aee_1364.log](https://github.com/srsolutionsag/SrMemberships/files/14062772/a2aee_1364.log)

I have tried multiple times, but the error is consistent. It happens when I copy&paste or when I manually input numbers, at random. Also I use "Immediate import". The error doesnt happen when using periodic import, however periodic import doesn't seem to do anything. 

Thanks

**Comment by chfsx** [comment]
Fixed in v1.1.0 and v2.1.0
