### ISSUE TITLE
 [ERROR] Identifier "global_screen" is not defined.

### ISSUE THREAD

**Issue by iFadi** [srsolutionsag/SrMemberships#3]
**On ILIAS v8.10 and SrMemberships v2.1.2**

When executing `php setup/setup.php update` in {ILIAS Root}
the following error occurs (s.screenshot):

` 
[ERROR] Identifier "global_screen" is not defined.                                                                         [45/4778]
                                                                                                                                     
         #0 /srv/spielwiese/ilias-luh/ILIAS/src/DI/Container.php(157): Pimple\Container->offsetGet()                                 
         #1 /srv/spielwiese/ilias-luh/ILIAS/src/GlobalScreen/Provider/AbstractProvider.php(47):                                      
         ILIAS\DI\Container->globalScreen()                                                                                          
         #2 /srv/spielwiese/ilias-luh/ILIAS/src/GlobalScreen/Scope/Tool/Provider/AbstractDynamicToolProvider.php(46):                
         ILIAS\GlobalScreen\Provider\AbstractProvider->globalScreen()                                                                
         #3 /srv/spielwiese/ilias-luh/ILIAS/src/GlobalScreen/Provider/PluginProviderHelper.php(39):                                  
         ILIAS\GlobalScreen\Scope\Tool\Provider\AbstractDynamicToolProvider->__construct()                                           
         #4                                                                                                                          
         /srv/spielwiese/ilias-luh/ILIAS/Customizing/global/plugins/Services/Cron/CronHook/SrMemberships/classes/class.ilSrMember    
         shipsPlugin.php(50): ILIAS\GlobalScreen\Scope\Tool\Provider\AbstractDynamicToolPluginProvider->__construct()                
         #5 /srv/spielwiese/ilias-luh/ILIAS/Services/Component/classes/class.ilPlugin.php(75): ilSrMembershipsPlugin->init()         
         #6                                                                                                                          
         /srv/spielwiese/ilias-luh/ILIAS/Customizing/global/plugins/Services/Cron/CronHook/SrMemberships/classes/class.ilSrMember    
         shipsPlugin.php(37): ilPlugin->__construct()                                                                                
         #7 /srv/spielwiese/ilias-luh/ILIAS/Services/Component/classes/class.ilComponentFactoryImplementation.php(48):               
         ilSrMembershipsPlugin->__construct()                                                                                        
         #8 /srv/spielwiese/ilias-luh/ILIAS/Services/Component/classes/Setup/class.ilComponentActivatePluginsObjective.php(94):      
         ilComponentFactoryImplementation->getPlugin()                                                                               
         #9 /srv/spielwiese/ilias-luh/ILIAS/src/Setup/CLI/ObjectiveHelper.php(59):                                                   
         ilComponentActivatePluginsObjective->achieve()                                                                              
         #10 /srv/spielwiese/ilias-luh/ILIAS/src/Setup/CLI/UpdateCommand.php(108):                                                   
         ILIAS\Setup\CLI\UpdateCommand->achieveObjective()                                                                           
         #11 /srv/spielwiese/ilias-luh/ILIAS/libs/composer/vendor/symfony/console/Command/Command.php(298):                          
         ILIAS\Setup\CLI\UpdateCommand->execute()                                                                                    
         #12 /srv/spielwiese/ilias-luh/ILIAS/libs/composer/vendor/symfony/console/Application.php(1040):                             
         Symfony\Component\Console\Command\Command->run()                                                                            
         #13 /srv/spielwiese/ilias-luh/ILIAS/libs/composer/vendor/symfony/console/Application.php(301):                              
         Symfony\Component\Console\Application->doRunCommand()                                                          
         #14 /srv/spielwiese/ilias-luh/ILIAS/libs/composer/vendor/symfony/console/Application.php(171):                 
         Symfony\Component\Console\Application->doRun()                                                                 
         #15 /srv/spielwiese/ilias-luh/ILIAS/setup/cli.php(40): Symfony\Component\Console\Application->run()            
         #16 /srv/spielwiese/ilias-luh/ILIAS/setup/setup.php(42): require_once('/srv/spielwiese...')                    
         #17 {main}                                                                                                     
`
<img width="1468" alt="Bildschirmfoto 2024-03-25 um 14 02 52" src="https://github.com/srsolutionsag/SrMemberships/assets/1717456/664d4dc0-d9a5-4112-843f-6835d6cba907">

**Comment by chfsx** [comment]
This has now been fixed with release v2.1.4

https://github.com/srsolutionsag/SrMemberships/releases/tag/v2.1.4
