### ISSUE TITLE
v2.1.4 breaks ILIAS v8.12 Style

### ISSUE THREAD

**Issue by iFadi** [srsolutionsag/SrMemberships#4]
After Upgrading to v2.1.4 the default ILIAS Style/Skin breaks (s.screenshots), when deactivating the plugin, the ILIAS Style/Skin is back to normal.

<img width="1470" alt="Bildschirmfoto 2024-06-06 um 06 13 11" src="https://github.com/srsolutionsag/SrMemberships/assets/1717456/4683fb27-5b04-4093-a09a-13507ef5b780">
<img width="1382" alt="Bildschirmfoto 2024-06-06 um 06 14 24" src="https://github.com/srsolutionsag/SrMemberships/assets/1717456/d2ed8398-669d-4f52-bf4f-5ba2d03d9547">

**Comment by chfsx** [comment]
This has been fixed in https://github.com/srsolutionsag/SrMemberships/releases/tag/v2.1.5, thanks for the report
